GET http://localhost:3000
###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name": "asmaa",
    "email": "asmaa@gmail.com",
    "password": "12345"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "asmaa@gmail.com",
    "password": "12345"
}
###
POST http://localhost:3000/match/create
Content-Type: application/json

{
    "firstPlayerId": "641c6ee5a1e611670c891b78"
}
###
POST http://localhost:3000/match/join/12033
Content-Type: application/json

{
    "secondPlayerId": "641cbe583dd44b3cde60322f"
}